const FullToShort: Map<string, string> = new Map([
  ['alabama', 'al'],
  ['alaska', 'ak'],
  ['arizona', 'az'],
  ['arkansas', 'ar'],
  ['california', 'ca'],
  ['colorado', 'co'],
  ['connecticut', 'ct'],
  ['delaware', 'de'],
  ['district of columbia', 'dc'],
  ['florida', 'fl'],
  ['georgia', 'ga'],
  ['hawaii', 'hi'],
  ['idaho', 'id'],
  ['illinois', 'il'],
  ['indiana', 'in'],
  ['iowa', 'ia'],
  ['kansas', 'ks'],
  ['kentucky', 'ky'],
  ['louisiana', 'la'],
  ['maine', 'me'],
  ['maryland', 'md'],
  ['massachusetts', 'ma'],
  ['michigan', 'mi'],
  ['minnesota', 'mn'],
  ['mississippi', 'ms'],
  ['missouri', 'mo'],
  ['montana', 'mt'],
  ['nebraska', 'ne'],
  ['nevada', 'nv'],
  ['new hampshire', 'nh'],
  ['new jersey', 'nj'],
  ['new mexico', 'nm'],
  ['new york', 'ny'],
  ['north carolina', 'nc'],
  ['north dakota', 'nd'],
  ['ohio', 'oh'],
  ['oklahoma', 'ok'],
  ['oregon', 'or'],
  ['pennsylvania', 'pa'],
  ['puerto rico', 'pr'],
  ['rhode island', 'ri'],
  ['south carolina', 'sc'],
  ['south dakota', 'sd'],
  ['tennessee', 'tn'],
  ['texas', 'tx'],
  ['utah', 'ut'],
  ['vermont', 'vt'],
  ['virginia', 'va'],
  ['virgin islands', 'vi'],
  ['washington', 'wa'],
  ['west virginia', 'wv'],
  ['wisconsin', 'wi'],
  ['wyoming', 'wy'],
]);

const ShortToFull: Map<string, string> = new Map([
  ['al', 'alabama'],
  ['ak', 'alaska'],
  ['az', 'arizona'],
  ['ar', 'arkansas'],
  ['ca', 'california'],
  ['co', 'colorado'],
  ['ct', 'connecticut'],
  ['de', 'delaware'],
  ['dc', 'district of columbia'],
  ['fl', 'florida'],
  ['ga', 'georgia'],
  ['hi', 'hawaii'],
  ['id', 'idaho'],
  ['il', 'illinois'],
  ['in', 'indiana'],
  ['ia', 'iowa'],
  ['ks', 'kansas'],
  ['ky', 'kentucky'],
  ['la', 'louisiana'],
  ['me', 'maine'],
  ['md', 'maryland'],
  ['ma', 'massachusetts'],
  ['mi', 'michigan'],
  ['mn', 'minnesota'],
  ['ms', 'mississippi'],
  ['mo', 'missouri'],
  ['mt', 'montana'],
  ['ne', 'nebraska'],
  ['nv', 'nevada'],
  ['nh', 'new hampshire'],
  ['nj', 'new jersey'],
  ['nm', 'new mexico'],
  ['ny', 'new york'],
  ['nc', 'north carolina'],
  ['nd', 'north dakota'],
  ['oh', 'ohio'],
  ['ok', 'oklahoma'],
  ['or', 'oregon'],
  ['pa', 'pennsylvania'],
  ['pr', 'puerto rico'],
  ['ri', 'rhode island'],
  ['sc', 'south carolina'],
  ['sd', 'south dakota'],
  ['tn', 'tennessee'],
  ['tx', 'texas'],
  ['ut', 'utah'],
  ['vt', 'vermont'],
  ['va', 'virginia'],
  ['vi', 'virgin islands'],
  ['wa', 'washington'],
  ['wv', 'west virginia'],
  ['wi', 'wisconsin'],
  ['wy', 'wyoming'],
]);

export function getStateNameByCode(code: string): string | undefined {
  return ShortToFull.get(code.toLowerCase());
}

export function getStateCodeByName(name: string): string | undefined {
  return FullToShort.get(name.replace(/[\s\-\_]+/g, ' ').toLowerCase())?.toUpperCase();
}
